### ISSUE TITLE
Is Useragent ratio correct?

### ISSUE THREAD

**Issue by samyk** [DIVERSIFY-project/amiunique#16]
Hi! Awesome project!

I noticed on various, common browsers on common OS's, User agent ratio always reported < 0.1%. Is that correct? Seems unlikely but could be true so I'd like to verify.

Some examples from three recent (but unique ;) machines:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.46 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36

**Comment by plaperdr** [comment]
Hi! Thanks for your interest in our project!

These ratios seem correct to me because they take our full history of fingerprints since the website was launched in November. 
For example, Version 44.0.2403.157 was released [last week](http://googlechromereleases.blogspot.fr/2015/08/stable-channel-update_20.html). If you take a look at our [stats page](https://amiunique.org/stats), we collected 1030 fingerprints in the past week. This means that if all devices that connected to AmIUnique.org in the past week were all Macs with the same browser, the ratio could be at most 1.2% (=1030*100/88346). Since not everyone is on Mac with the same browser and the same browser version, it does not surprise me that the ratio is under 0.1%.

What our website does not reflect is the browser market share at a specific time. If we were to collect 80 000 fingerprints on a single day, you would see that this ratio is clearly above 1% and maybe a lot more than that. If you take a look at the stats for the past week, you can see that Chrome 44 (the current stable version of Chrome) represents two thirds of the collected Chrome fingerprints. But, since we take all the fingerprints that we collected on a large time span to calculate our ratios, you get these results that may be surprising.

If I was not clear and if you want more clarifications, don't hesitate to ask! :)

**Comment by samyk** [comment]
I see. Very cool -- I'd mention that the fingerprint uniqueness is only a
snapshot in time and not relevant over a period, but regardless I think
it's cool what you're doing! Good work.

On Wed, Aug 26, 2015 at 1:00 AM, Pierre Laperdrix <notifications@github.com>
wrote:

> Hi! Thanks for your interest in our project!
>
> These ratios seem correct to me because they take our full history of
> fingerprints since the website was launched in November.
> For example, Version 44.0.2403.157 was released last week
> <http://googlechromereleases.blogspot.fr/2015/08/stable-channel-update_20.html>.
> If you take a look at our stats page <https://amiunique.org/stats>, we
> collected 1030 fingerprints in the past week. This means that if all
> devices that connected to AmIUnique.org in the past week were all Macs with
> the same browser, the ratio could be at most 1.2% (=1030*100/88346). Since
> not everyone is on Mac with the same browser and the same browser version,
> it does not surprise me that the ratio is under 0.1%.
>
> What our website does not reflect is the browser market share at a
> specific time. If we were to collect 80 000 fingerprints on a single day,
> you would see that this ratio is clearly above 1% and maybe a lot more than
> that. If you take a look at the stats for the past week, you can see that
> Chrome 44 (the current stable version of Chrome) represents two thirds of
> the collected Chrome fingerprints. But, since we take all the fingerprints
> that we collected on a large time span to calculate our ratios, you get
> these results that may be surprising.
>
> If I was not clear and if you want more clarifications, don't hesitate to
> ask! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIVERSIFY-project/amiunique/issues/16#issuecomment-134889520>
> .
>



-- 
@SamyKamkar <https://twitter.com/samykamkar>
http://samy.pl
