### ISSUE TITLE
Yes and No answer reversed

### ISSUE THREAD

**Issue by kajover** [DIVERSIFY-project/amiunique#45]
After testing your fingerprint the following answer needs to be reversed.

"Are you unique?
Yes! (You can be tracked!)"

This should actually be a "No!"

EDIT: completely wrong, sorry for the confusion..

**Comment by plaperdr** [comment]
Hi! Thanks a lot for your interest in AmIUnique!
I'm not sure I understand what the problem is here. If someone has a fingerprint that is unique, that means he or she can be tracked online without the need to rely on cookies or other identification techniques.
So if the FP is unique, it is "Yes!" and if the FP is not unique, it is "No!".

**Comment by andysavage** [comment]
you are right, sorry I'll go back to sleep!

**Comment by kajover** [comment]
@plaperdr You are absolutely right. I had a brainfart moment here. Please close/delete the ticket.
